### ISSUE TITLE
Random seed in LocalOptimization is fixed

### ISSUE THREAD

**Issue by vlarsson** [tsattler/RansacLib#11]
In LocalOptimization the random seed is always reset to options.random_seed_. Since this method is called multiple times, this probably not the desired behavior.

https://github.com/tsattler/RansacLib/blob/565718ff44657b3e5782bda0844f863ae8653f62/RansacLib/ransac.h#L353-L357

**Comment by tsattler** [comment]
Resolved in PR #12
