### ISSUE TITLE
What is the difference between RansacLib and openGV？

### ISSUE THREAD

**Issue by robot-mh** [tsattler/RansacLib#14]
Hi @tsattler ,
 As there are currently three dependencies include openGV, opengv also have many different SAC problems. What is the difference between RansacLib and openGV？

**Comment by tsattler** [comment]
RansacLib is my implementation of some RANSAC algorithms. OpenGV also provides *SAC implementations, but is only a dependency for the examples (which are meant to show how to use RansacLib). RansacLib might be a bit more generic and more generally applicable, but it is up to you what you want to use.
