### ISSUE TITLE
Hybrid Ransac

### ISSUE THREAD

**Issue by JayYe99** [tsattler/RansacLib#17]
Hi! I'm highly interested in the Hybrid Ransac, while it seems that the Hybrid Ransac is not compiled in the pyransaclib. 
And the LocallyOptimizedHybridMSAC implementation is not in this repo. 
Could you please shed some light on how to perform visual localization with it?

**Comment by tsattler** [comment]
Thanks for the question. There was a typo in the README regarding the naming of the hybrid RANSAC class. I just fixed it.

Did you had a look at the example for using hybrid RANSAC for line estimation? If you want to use it for visual localization, you will need (minimal) solvers that can use some combination of 2D-2D and 2D-3D matches for pose estimation. These solvers can then be called in the `nt MinimalSolver(const std::vector<int>& sample, ModelVector* models) const` function that needs to be implemented.

**Comment by Jay-Ye** [comment]
Thanks for your reply and suggestions. I'll have a try.
