### ISSUE TITLE
LO-RANSAC: Least squares step before iterative least squares refinement needed?

### ISSUE THREAD

**Issue by atasoglou** [tsattler/RansacLib#19]
In the [local optimization step](https://github.com/tsattler/RansacLib/blob/b952083fcf1b2aea001bf178e010e540ff372889/RansacLib/ransac.h#L341) of the  [LO-RANSAC](https://github.com/tsattler/RansacLib/blob/b952083fcf1b2aea001bf178e010e540ff372889/RansacLib/ransac.h#L121) just before the iterative least squares refinement there is again a LSQ fit. Is that really doing anything?

So is this [line](https://github.com/tsattler/RansacLib/blob/b952083fcf1b2aea001bf178e010e540ff372889/RansacLib/ransac.h#L391) doing anything? Is this step needed?

Thanks!

**Comment by tsattler** [comment]
This step is used to polish the most recently found model as to recover as many inliers as possible for the least squares fit. In some cases, this might not be necessary, but in general, I recommend using it.
