### ISSUE TITLE
Is the original RANSAC implemented ?

### ISSUE THREAD

**Issue by alexs7** [tsattler/RansacLib#20]
I have been trying to use the original version of RANSAC but I can't seem to find a way to do so. 
Are only the variants implemented ?
In `ransac.h` there is a `LocallyOptimizedMSAC` class only. Is it the case that using certain options it behaves like RANSAC?

**Comment by tsattler** [comment]
No, it is not implemented. It should not be hard to change it to standard RANSAC though (use inlier counting instead of the MSAC cost function and disable local optimization). Then again, I cannot recommend using standard RANSAC.

**Comment by alexs7** [comment]
ok thank you!
