### ISSUE TITLE
Multiple models estimated ?

### ISSUE THREAD

**Issue by alexs7** [tsattler/RansacLib#22]
Hello,

I had a look in the source code and I have a question about this code in `ransac.h`:

```
      // MinimalSolver returns the number of estimated models.
      const int kNumEstimatedModels =
          solver.MinimalSolver(minimal_sample, &estimated_models);
      if (kNumEstimatedModels <= 0) continue;
```

I don't understand how it is expected to return multiple solutions with 1 sample. For example, in the P3P case, if I pass the minimum number of points i.e. 4, then the solver will return 1 solution, 1 model ? Why does it expect multiple models ?

**Comment by tsattler** [comment]
Minimal solvers typically return multiple solutions. For example, the P3P solver takes 3 points as input and returns up to 4 solutions. A 4th point can be used to disambiguate these solutions, which is done in the example implementation provided.

**Comment by alexs7** [comment]
Ok thanks!
